dbus-top: use mvwaddstr when no arguments are needed
Currently, some of the code uses mvwprintw to print a string without
using a format string, this causes the following errors:

error: format not a string literal and no format arguments
[-Werror=format-security]

The fix is to use mvwaddstr when no arguments are needed.

Signed-off-by: Sui Chen <suichen@google.com>
Change-Id: Ib17ad7a7795cb7bf77161f8730139f38216b7aba
(cherry picked from commit 58f2806fe8400e0f9663c4fd58955521c6f5794d)